### PR TITLE
Translate to Chinese simplified

### PR DESCRIPTION
**Pull request by yvesyao**
Hey guys,
I recently translated this post to Chinese and it's finished now.
It should be much pleasured if you could spend some time on reviewing this PR.
Please let me know when you find some errors.
Thanks!

### CODE REVIEW

**Comment by js-kyle** [comment]
@yvesyao That's amazing work!

Ping @goldbergyoni

**Comment by goldbergyoni** [comment]
@yvesyao Wow! Amazing work man, many many thanks 🎖 😮 

Few notes:
1. Merged
2. I'll put a flag very soon with your name and link on the top of the home page. Do you prefer your GH handle or full name?
3. Are there any Chinese forums/groups to publish this?

**Comment by goldbergyoni** [comment]
@js-kyle Feel free to merge or anything you feel like

**Comment by yvesyao** [comment]
> @yvesyao Wow! Amazing work man, many many thanks 🎖 😮
> 
> Few notes:
> 
> 1. Merged
> 2. I'll put a flag very soon with your name and link on the top of the home page. Do you prefer your GH handle or full name?
> 3. Are there any Chinese forums/groups to publish this?

1. Thanks :]
2. GH handle is fine.
3. No.

**Comment by goldbergyoni** [comment]
@yvesyao  I will put a flag link with your name at the top of the English page by tomorrow 🎈 🎂

**Comment by goldbergyoni** [comment]
@yvesyao Now on the home page. Thanks again for the amazing work!!

**Comment by yvesyao** [comment]
> @yvesyao Now on the home page. Thanks again for the amazing work!!

Thanks :)

**Pull request merged**
