### PR TITLE
Persian Translate

### PR DESCRIPTION
**Pull request by TREER00T**

### CODE REVIEW

**Review by TREER00T — COMMENTED** [review]
The changes in this part are related to solving the problem in this issue

**Comment by goldbergyoni** [comment]
@TREER00T WOW, this is so awesome!

First, sorry for the very late reply, I was away from OSS work for a few months due to some circumstances

This PR is gorgeous, many-many thanks for this

I'll try to promote this as much as possible - Twitter, news section in my repos, etc

Is there a Persian FB/Whatsapp group where we can publish this?

@all-contributors please add @TREER00T for content

**Comment by goldbergyoni** [comment]
@TREER00T 🎁 One last note - I'm now finalizing a 7-hours long comprehensive, advanced Node.js testing course - I'd like to gift to you as my way of saying that you for this awesome work

I'll bounce in a month+

**Comment by TREER00T** [comment]
> @TREER00T WOW, this is so awesome!
> 
> First, sorry for the very late reply, I was away from OSS work for a few months due to some circumstances
> 
> This PR is gorgeous, many-many thanks for this
> 
> I'll try to promote this as much as possible - Twitter, news section in my repos, etc
> 
> Is there a Persian FB/Whatsapp group where we can publish this?
> 
> @all-contributors please add @TREER00T for content

Hello, there is no problem, but regarding the WhatsApp group, I must say no, most of the software development groups are created in Telegram, but do not worry about it, the necessary notifications will be made in Telegram.

**Comment by TREER00T** [comment]
@goldbergyoni I will be very happy to continue the development of the software with you

**Pull request merged**
