### PR TITLE
Update: README (KR)

### PR DESCRIPTION
**Pull request by evannilaz-zz**
Some READMEs need to be translated properly. There is a lot of difficulty reading documents other than English README. I can even say that it would be better to read English version README with local translater rather than reading document provided in the repo.

### CODE REVIEW

**Comment by goldbergyoni** [comment]
@elitance Welcome aboard and thanks for making the testing best practices even better!

@ragubyun Would you kindly review this as your the owner of the Korean translation?

**Comment by elitance** [comment]
@goldbergyoni This PR edits only part of the manual. I'll try to edit the whole manual with smoother translation later if time permits..

**Comment by ragubyun** [comment]
@goldbergyoni Sure! I'll follow up.

@elitance Thank you for your hard work to make better. I look forward to improved translation.

**Comment by goldbergyoni** [comment]
@ragubyun Just a reminder in case you forgot about this. If you need more time - No worries at all, do it at your convenience

**Comment by ragubyun** [comment]
@goldbergyoni This PR contains too few revisions of all, so I'm waiting for more meaningful revisions.

**Comment by evannilaz** [comment]
@ragubyun I've done few more revisions, but since it's length is tremendous, I think it'll take some time to fully edit. I'll do my best to complete this work.

**Comment by goldbergyoni** [comment]
@ragubyun I follow your instructions, you're the chief of this PR

**Comment by goldbergyoni** [comment]
@evannilaz @ragubyun Your call wether it's 'good enough' or shall we wait. Anyway, take your time:)

**Review by rain-axb — COMMENTED** [review]
기존에 번역을 진행할 때 여러명이 함께 작업을 하였고,
그 당시에 Guide, ex), Note 등을 그대로 쓰지않고 번역을 하는것으로 룰 정하였습니다.
참고해주세요.

그리고 소스코드 혹은 테스트코드에 있는 문장을 번역한 이유도 어떠한 의미인지 더 잘 전달하기 위함입니다.
의미가 잘못 번역 되었거나 빠진 내용이 있다면 그 부분을 채우는쪽에 집중해주시는게 좋을 것 같습니다🙏

시간이 허락하지 않아서 빠른 피드백을 드리지 못해서 죄송합니다.

**Pull request closed without merging**
