### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by mel-mouk**
Starting point for french translation

### CODE REVIEW

**Comment by goldbergyoni** [comment]
@mel-mouk Great start!!

Let's merge to 'translations-draft-french'?

**Comment by goldbergyoni** [comment]
Other words - PR to translations-draft-french so we keep the progress also here

**Comment by mel-mouk** [comment]
We can do that if you want, will it change something for me ? ( do I have to create a new PR for each change if we merge to a draft branch or does it stay the same ? It's my first contribution of this kind )

**Comment by goldbergyoni** [comment]
No need to change anything in your workflow, just an opportunity to share
the state with others here and save occasionally, from time to time. It's
optional. Whatever is convenient for you:)

**Comment by mel-mouk** [comment]
I created the PR

**Comment by goldbergyoni** [comment]
Not related

@all-contributors please add @arnnis  for content

**Comment by mel-mouk** [comment]
@goldbergyoni About the bullet 2.2, I actually wrote an article on that topic with some examples: https://javascript.plainenglish.io/dont-skip-api-testing-rethink-it-49139b848f08 

If you think the article is good enough, can I add it to the code example section?

**Comment by mel-mouk** [comment]
@goldbergyoni Hi, I'm finally done with the translation. If any other french speaker want to proofread that would be great but I think we can merge for now

**Comment by goldbergyoni** [comment]
@mel-mouk wow my apology, had some notifications issues and I missed 3 PRs here 😞😮

This looks so amazinggg. I wish I've seen this before. Merging immediately. 

Are there some French newsgroups/FB where we can publish this great work?

**Comment by mel-mouk** [comment]
No worries :) I don't really know the french groups actually :/

**Pull request merged**
