### PR TITLE
Translations pt br staging

### PR DESCRIPTION
**Pull request by iagocavalcante**
Hey all,

It is in progress.

### CODE REVIEW

**Comment by js-kyle** [comment]
@iagocavalcante nice progress!

**Comment by goldbergyoni** [comment]
@iagocavalcante Awesome! 

Let us know when it's ready enough to be promoted and referred from the global home page?

**Comment by iagocavalcante** [comment]
I'll notify you, i recent paused this, because my son will born today. Thanks for the reply.

**Comment by goldbergyoni** [comment]
@iagocavalcante Spend time with your son! Many wishes from us, hope everything went well

**Comment by DouglasMV** [comment]
@iagocavalcante i will help you translate, already tanslated Section 3, and made a PR at your branch.

**Comment by goldbergyoni** [comment]
@DouglasMV Sounds amazing ❤️

**Pull request merged**
