### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by sanguino**
This is my Spanish translation proposal (https://github.com/goldbergyoni/javascript-testing-best-practices/issues/99)

I will check all text again to remove typos and refactor some of the first bullets to have the same "language" in all the the bullets

Do you want me to squash the commits in one?

Thanks!

### CODE REVIEW

**Comment by sanguino** [comment]
Closes #99

**Comment by goldbergyoni** [comment]
@sanguino WOW, WOW, I missed this PR. Looking in an hour or two! 💜

**Comment by goldbergyoni** [comment]
@sanguino That looks amazing. No need to squash. 

What is the status of this, putting a side typos: 100% translated, 80%?

If 100%, shall we link to it from the home page?

**Comment by goldbergyoni** [comment]
@all-contributors please add @sanguino for content

**Comment by sanguino** [comment]
I think is ok to be in the home page but I'll do another PR to remove some typos and refactor some of the first bullets to have the same "language" in all the the bullets

Thanks!

**Comment by goldbergyoni** [comment]
@sanguino Awesome!

Let's then:
1. Typos PR
2. Put a link in Homepage + news, I can do this
3. Tweet, what is your Twitter handle?
4. Create a release, I can do this
5. Put your name at the top of the Spanish page

Cool?

**Comment by sanguino** [comment]
Cool!

I will do it this weekend. 🙂

Thanks!

**Comment by sanguino** [comment]
I created a new pull request with points 1 and 5, and I put a link to Spanish translation in Homepage
My twitter is `@sanguinoide`

If you need me anything else, please let me know.

Thanks!

**Pull request merged**
