### PR TITLE
Make edits to Sections 1.2 - 1.6

### PR DESCRIPTION
**Pull request by jaimemendozadev**
Changes include style and content edits.

### CODE REVIEW

**Comment by goldbergyoni** [comment]
Welcome aboard ✋

Many thanks for your help in making this knowledge more accurate and readable 🚀

I'm OOO, looking into this in the really soon next following days

**Comment by jaimemendozadev** [comment]
You're welcome! 👍  Look forward to your talk at js.la in Los Angeles next week! 🎉 Hopefully I can make it. 😬

**Comment by goldbergyoni** [comment]
@jaimemendozadev Were you at the LA meetup finally??

Went now over all these enhancements - thank you, those are great improvements! I took my time to read slowly and learn so I can avoid those mistakes next time. This is a great help for non-native English speaker like me. 

Adding your name of course to the credits section (coming soon).

**Comment by jaimemendozadev** [comment]
I'm no English major 😬 but when I see something where I know I can make an improvement without removing the spirit/meaning of the author's intent, happy to help!

For a non-native English speaker, I understood your prose and thought it was awesome! 🚀 😄 Keep up the excellent work! 

Will continue making edits if I get the chance to finish the docs.

**Pull request merged**
