### PR TITLE
Translate into Korean.

### PR DESCRIPTION
**Pull request by ragubyun**
Hi, gold.

I want to say thank you first. Your repo is awesome!

So I want to let other Koreans see it as well, I just getting started to translate.

It is in progress.

### CODE REVIEW

**Comment by js-kyle** [comment]
Nice progress!

**Comment by BrunoScheufler** [comment]
Awesome work, looking forward to seeing this grow 🙌

**Comment by goldbergyoni** [comment]
> I want to say thank you first. Your repo is awesome!

Thank you, really glad to hear these words! 🙏 

I'm mering this progress, LMK once it's mature enough so I'll put a flag, link and announcement at the home page?

**Comment by ragubyun** [comment]
Thanks for merging!

I'll let you know once more than 70% of the translations are made.

**Comment by goldbergyoni** [comment]
@ragubyun cool

**Pull request merged**
