### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by sanguino**
Corrected some typos, rewritten some parts, added link to Spanish readme at main readme

### CODE REVIEW

**Review by goldbergyoni — APPROVED** [review]
LGTM, well at least the English part:)

**Comment by goldbergyoni** [comment]
@sanguino That's hilarious, amazing milestone for this repo 💜

Did you add your name to the Spanish name? What's your Twitter handle?

@all-contributors please add @sanguino  for content

**Comment by goldbergyoni** [comment]
@all-contributors please add @sanguino for content

**Comment by sanguino** [comment]
> @sanguino That's hilarious, amazing milestone for this repo 💜
> 
> Did you add your name to the Spanish name? What's your Twitter handle?
> 
> @all-contributors please add @sanguino for content

Yes I added my name. My Twitter handle is `@sanguinoide`

**Pull request merged**
