### PR TITLE
Update code example of 3.9

### PR DESCRIPTION
**Pull request by yubinTW**

### CODE REVIEW

**Review by goldbergyoni — COMMENTED** [review]
Welcome aboard 🌻 and thanks for fixing these embarrassing mistakes 😞

Why is there a new file, readme-zh-TW?

**Comment by yubinTW** [comment]
Hello, I am going to translate to Taiwanese mandarin (zh-tw). 
sorry for my mistake to mix them in this PR

**Comment by yubinTW** [comment]
I had fixed the commits, please review it

**Comment by goldbergyoni** [comment]
@yubinTW Great fix!

There is going to be a link to this repo from some big newsletters in 2 days. If you have your translation >60% ready, consider PRing quickly

@all-contributors please add @yubinTW  for code

**Pull request merged**
